version: '3.0'
services:
    paybright-app:
        build:
            context: .
            args:
                BUILD: Debug
                GHUSER: ISatByTheO
                GHPWD: f8ec45e9351df31fca9997f9936170cc46ded823

        environment:
            - ASPNETCORE__ENVIRONMENT=Development
            - "applicationcontext=Server=192.168.2.10;Database=Application;User Id=sa;Password=abc123!;"
            - "ASPNETCORE__URLS=https://+;http://+"
            - Kestrel__Certificates__Default__Path=/app/cert.pfx
            - Kestrel__Certificates__Default__Password=password  
        ports:
            - 8000:80
            - 8001:443
